Importing the Dependencies

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

Data Collection and Analysis

PIMA Diabetes Dataset

In [2]:
# loading the diabetes dataset to a pandas DataFrame
# from google.colab import drive
# drive.mount('/content/drive')
autism_dataset = pd.read_csv("asd_data_csv.csv")
#autism_dataset = pd.read_csv("/content/asd_data_csv.csv")

In [3]:
# printing the first 5 rows of the dataset
autism_dataset.head()

Social_Responsiveness_Scale  Age_Years  Speech Delay/Language Disorder  \
0                            3          2                               1   
1                            6          3                               1   
2                            7          3                               1   
3                            1          2                               1   
4                            3          2                               1   

   Learning disorder  Genetic_Disorders  Depression  \
0                  1                  1           1   
1                  1                  1           1   
2                  1                  1           1   
3                  1                  0           1   
4                  1                  0           1   

   Global developoental delay/intellectual disability  \
0                                                  1    
1                                                  1    
2                                                  1    
3                                                  1    
4                                                  1    

   Social/Behavioural Issues  Anxiety_disorder  Sex  Jaundice  \
0                          1                 1    1         1   
1                          1                 1    0         1   
2                          1                 1    0         1   
3                          1                 1    0         0   
4                          1                 1    1         0   

   Family_member_with_ASD  Outcome  
0                       0        0  
1                       0        1  
2                       0        1  
3                       0        1  
4                       0        1

In [4]:
# number of rows and Columns in this dataset
autism_dataset.shape

(1961, 13)

In [5]:
# getting the statistical measures of the data
autism_dataset.describe()

Social_Responsiveness_Scale    Age_Years  \
count                  1961.000000  1961.000000   
mean                      3.083631     9.618052   
std                       3.691156     4.301336   
min                       0.000000     1.000000   
25%                       0.000000     7.000000   
50%                       1.000000     9.000000   
75%                       5.000000    14.000000   
max                      10.000000    18.000000   

       Speech Delay/Language Disorder  Learning disorder  Genetic_Disorders  \
count                     1961.000000        1961.000000        1961.000000   
mean                         0.527282           0.535951           0.505354   
std                          0.499382           0.498833           0.500099   
min                          0.000000           0.000000           0.000000   
25%                          0.000000           0.000000           0.000000   
50%                          1.000000           1.000000           1.000000   
75%                          1.000000           1.000000           1.000000   
max                          1.000000           1.000000           1.000000   

        Depression  Global developoental delay/intellectual disability  \
count  1961.000000                                        1961.000000    
mean      0.525752                                           0.525752    
std       0.499464                                           0.499464    
min       0.000000                                           0.000000    
25%       0.000000                                           0.000000    
50%       1.000000                                           1.000000    
75%       1.000000                                           1.000000    
max       1.000000                                           1.000000    

       Social/Behavioural Issues  Anxiety_disorder          Sex     Jaundice  \
count                1961.000000       1961.000000  1961.000000  1961.000000   
mean                    0.525752          0.524222     0.272820     0.771545   
std                     0.499464          0.499540     0.445523     0.419944   
min                     0.000000          0.000000     0.000000     0.000000   
25%                     0.000000          0.000000     0.000000     1.000000   
50%                     1.000000          1.000000     0.000000     1.000000   
75%                     1.000000          1.000000     1.000000     1.000000   
max                     1.000000          1.000000     1.000000     1.000000   

       Family_member_with_ASD      Outcome  
count             1961.000000  1961.000000  
mean                 0.327384     0.538501  
std                  0.469378     0.498643  
min                  0.000000     0.000000  
25%                  0.000000     0.000000  
50%                  0.000000     1.000000  
75%                  1.000000     1.000000  
max                  1.000000     1.000000

In [6]:
autism_dataset['Outcome'].value_counts()

Outcome
1    1056
0     905
Name: count, dtype: int64

0 --> Not with ASD

1 --> With ASD

In [7]:
autism_dataset.groupby('Outcome').mean()

Social_Responsiveness_Scale  Age_Years  \
Outcome                                           
0                           1.942541   9.717127   
1                           4.061553   9.533144   

         Speech Delay/Language Disorder  Learning disorder  Genetic_Disorders  \
Outcome                                                                         
0                              0.354696           0.367956           0.340331   
1                              0.675189           0.679924           0.646780   

         Depression  Global developoental delay/intellectual disability  \
Outcome                                                                   
0          0.353591                                           0.352486    
1          0.673295                                           0.674242    

         Social/Behavioural Issues  Anxiety_disorder       Sex  Jaundice  \
Outcome                                                                    
0                         0.353591          0.352486  0.469613  0.704972   
1                         0.673295          0.671402  0.104167  0.828598   

         Family_member_with_ASD  
Outcome                          
0                      0.184530  
1                      0.449811

In [8]:
# separating the data and labels
X = autism_dataset.drop(columns = 'Outcome', axis=1).values
Y = autism_dataset['Outcome'].values

In [9]:
print(X)

[[ 3  2  1 ...  1  1  0]
 [ 6  3  1 ...  0  1  0]
 [ 7  3  1 ...  0  1  0]
 ...
 [ 1  7  0 ...  0  0  0]
 [ 0 14  0 ...  0  0  0]
 [ 1  7  0 ...  0  0  0]]


In [10]:
print(Y)

[0 1 1 ... 1 0 1]


Data Standardization

In [11]:
scaler = StandardScaler()

In [12]:
scaler.fit(X)

StandardScaler()

In [13]:
standardized_data = scaler.transform(X)

In [14]:
print(standardized_data)

[[-0.02266285 -1.77154153  0.94684654 ...  1.63261158  0.54415114
  -0.69766208]
 [ 0.7902979  -1.53899632  0.94684654 ... -0.61251556  0.54415114
  -0.69766208]
 [ 1.06128481 -1.53899632  0.94684654 ... -0.61251556  0.54415114
  -0.69766208]
 ...
 [-0.56463669 -0.60881547 -1.05613735 ... -0.61251556 -1.83772472
  -0.69766208]
 [-0.8356236   1.01900103 -1.05613735 ... -0.61251556 -1.83772472
  -0.69766208]
 [-0.56463669 -0.60881547 -1.05613735 ... -0.61251556 -1.83772472
  -0.69766208]]


In [15]:
X = standardized_data
Y = autism_dataset['Outcome'].values

In [16]:
print(X)
print(Y)

[[-0.02266285 -1.77154153  0.94684654 ...  1.63261158  0.54415114
  -0.69766208]
 [ 0.7902979  -1.53899632  0.94684654 ... -0.61251556  0.54415114
  -0.69766208]
 [ 1.06128481 -1.53899632  0.94684654 ... -0.61251556  0.54415114
  -0.69766208]
 ...
 [-0.56463669 -0.60881547 -1.05613735 ... -0.61251556 -1.83772472
  -0.69766208]
 [-0.8356236   1.01900103 -1.05613735 ... -0.61251556 -1.83772472
  -0.69766208]
 [-0.56463669 -0.60881547 -1.05613735 ... -0.61251556 -1.83772472
  -0.69766208]]
[0 1 1 ... 1 0 1]


Train Test Split

In [17]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, stratify=Y, random_state=2)

In [18]:
print(X.shape, X_train.shape, X_test.shape)

(1961, 12) (1568, 12) (393, 12)


Training the Model

In [19]:
classifier = svm.SVC(kernel='linear')

In [20]:
#training the support vector Machine Classifier
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

Model Evaluation

Accuracy Score

In [21]:
# accuracy score on the training data
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [22]:
print('Accuracy score of the training data : ', training_data_accuracy)

Accuracy score of the training data :  0.6919642857142857


In [23]:
# accuracy score on the test data
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [24]:
print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the test data :  0.7302798982188295


Making a Predictive System

In [25]:
# input_data = (3,18,1,1,1,1,1,1,2,1,0,1,1)
input_data = (0,4,0,0,0,0,0,0,1,0,1,1,0)
# input_data = (0,4,1,1,1,1,1,1,1,1,1,1,1)

# changing the input_data to numpy array

input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)[:, :12]

# standardize the input data
std_data = scaler.transform(input_data_reshaped)
print(std_data)

prediction = classifier.predict(std_data)
print(prediction)

if (prediction[0] == 0):
  print('The person is not with Autism spectrum disorder')
else:
  print('The person is with Autism spectrum disorder')

[[-0.8356236  -1.30645111 -1.05613735 -1.0746837  -1.01076678 -1.05290178
  -1.05290178 -1.05290178  0.95267389 -0.61251556  0.54415114  1.43335869]]
[1]
The person is with Autism spectrum disorder


In [26]:
import pickle

In [27]:
#pickle.dump(autism_dataset,open("autism_dataset.pkl","wb"))